### ISSUE TITLE
Nuget package update

### ISSUE THREAD

**Issue by catfly1** [quamotion/androidxmldotnet#20]
It appears that the latest nuget package at https://www.nuget.org/packages/androidxml/ (ver 1.1.14) is missing the following commit:

https://github.com/quamotion/androidxmldotnet/commit/2ae38a470e50eae7550ff97b4e12869f97aa5107

If the nuget package could be updated then I can remove some kludge reflection from my code :)!

**Comment by qmfrederik** [comment]
Ah, you're right.
I just pushed 1.1.17 to NuGet. Should be visible in a while.
